version: '3.4'

services:
  f1.api:
    image: ${DOCKER_REGISTRY-}f1api
    build:
      context: .
      dockerfile: Services/F1/F1.API/Dockerfile

  f1db.postgres:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  rabbitmq:
    image: rabbitmq:3-management-alpine

  seed:
    image: ${DOCKER_REGISTRY-}seed
    build:
      context: .
      dockerfile: Services/Seed/Seed/Dockerfile

volumes:
  postgres_data:
  pgadmin_data:
